application: mealsloth-chimera-ap01
version: 1
runtime: python27
api_version: 1
threadsafe: true


skip_files:
- ^(.*/)?.*\.pyc$
- ^(.*/)?.*\.less$
- ^(.*/)?.*\.DS_Store$
- ^(.*/)?.*\.csslintrc$


handlers:
- url: /.*
  script: main.app


libraries:
- name: django
  version: "latest"
- name: MySQLdb
  version: "latest"